protected/modules/priceAdmin/controllers/ProductController.php
<?php

Yii::import('application.models.Product');

class ProductController extends Controller{

    /**
     * @return array action filters
     */
    public function filters()
    {
        return array(
            'accessControl', // perform access control for CRUD operations
            'postOnly + delete', // we only allow deletion via POST request
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules()
    {
        return array(
            array('allow',  // allow all users to perform 'index' and 'view' actions
                'actions' => array_unique(array_map(
                    function($el){
                        return strstr($el, 'action') ? preg_replace(array('/actions/', '/action/'), '', $el) : '';
                    },
                    get_class_methods(__CLASS__)
                )),
                'roles' => array(User::ROLE_ADMIN),
            ),
            array('deny',  // deny all users
                'users' => array('*'),
            ),
        );
    }

    public function actionIndex(){

        $model = Product::model();

        $this->render('index', array('model'=> $model));
    }

    /**
     * @param $id
     * @throws CDbException
     */
    public function actionDelete($id){

        if(isset($id) && !empty($id) && is_numeric($id)){
            if (($model = Product::model()->findByPk($id)) !== null) {
                $model->delete();
            }
        }
    }

    public function actionCreate(){

        $model=new Product();

        if(isset($_POST['Product'])){

            $model=new Product();
            $trModel = new TrProduct();

            $model->attributes=$_POST['Product'];

            if($model->validate()){
                $model->save();

                $trModel->setAttribute('name', $_POST['Product']['name']);
                $trModel->setAttribute('trParentId', $model->id);
                $trModel->setAttribute('param', $_POST['Product']['param']);
                $trModel->setAttribute('langId', Yii::app()->language);

                if(!$trModel->save()){
                    $trModel->getErrors();
                }

                $this->redirect(array('index'));
            }else{
                $model->getErrors();
            }

        }
        $this->render('create',array(
            'model'=>$model,
        ));
    }

    /**
     * @param $id
     */
    public function actionUpdate($id)
    {
        $model = Product::model()->findByPk($id);
        $trModel = TrProduct::model()->findByAttributes(['trParentId' => $id, 'langId' => Yii::app()->language]);

        if(isset($_POST['Product'])){

            if($model->validate()){
                $model->save();

                $trModel->setAttribute('name', $_POST['ProductCategory']['name']);
                $trModel->setAttribute('description', $_POST['ProductCategory']['param']);

                if(!$trModel->save())
                    $trModel->getErrors();

                $this->redirect(array('index'));
            }else{
                $model->getErrors();
            }

        }
        $this->render('update',array(
            'model'=>$model,
        ));
    }
}

protected/modules/priceAdmin/controllers/ProductPriceController.php
<?php
class ProductPriceController extends Controller{

    /**
     * @return array action filters
     */
    public function filters()
    {
        return array(
            'accessControl', // perform access control for CRUD operations
            'postOnly + delete', // we only allow deletion via POST request
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules()
    {
        return array(
            array('allow',  // allow all users to perform 'index' and 'view' actions
                'actions' => array_unique(array_map(
                    function($el){
                        return strstr($el, 'action') ? preg_replace(array('/actions/', '/action/'), '', $el) : '';
                    },
                    get_class_methods(__CLASS__)
                )),
                'roles' => array(User::ROLE_ADMIN),
            ),
            array('deny',  // deny all users
                'users' => array('*'),
            ),
        );
    }

    public function actionIndex(){

        $model = ProductPrice::model();

        $this->render('index', array('model'=> $model));
    }

    /**
     * @param $id
     * @throws CDbException
     */
    public function actionDelete($id){

        if(isset($id) && !empty($id) && is_numeric($id)){
            if (($model = ProductPrice::model()->findByPk($id)) !== null) {
                $model->delete();
            }
        }
    }

    public function actionCreate(){

        $model=new ProductPrice();

        if(isset($_POST['ProductPrice'])){

            $model=new ProductPrice();
            $model->attributes=$_POST['ProductPrice'];

            if($model->validate()){
                $model->save();

                $this->redirect(array('index'));
            }else{
                $model->getErrors();
            }

        }
        $this->render('create',array(
            'model'=>$model,
        ));
    }

    /**
     * @param $id
     */
    public function actionUpdate($id)
    {
        $model=ProductPrice::model()->findByPk($id);

        if(isset($_POST['ProductPrice'])){

            $model->attributes=$_POST['ProductPrice'];

            if($model->validate()){
                $model->update();

                $this->redirect(array('index'));
            }else{
                $model->getErrors();
            }

        }
        $this->render('update',array(
            'model'=>$model,
        ));
    }
}

protected/modules/priceAdmin/views/productPrice/_form.php
<?php
/* @var $this ProductController */
/* @var $model Product */
/* @var $form CActiveForm */

Yii::import('application.models.Product');

?>

<?php
	echo TbHtml::linkButton('Назад', array(
		'class' => 'btn pull-right btn-warning',
		'style' => 'margin:10px 50px 0px 0px;',
		'url' => $this->createUrl('product/index'),
	));
?>
<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'ProductPrice-form',
	// Please note: When you enable ajax validation, make sure the corresponding
	// controller action is handling ajax validation correctly.
	// There is a call to performAjaxValidation() commented in generated controller code.
	// See class documentation of CActiveForm for details on this.
	'enableAjaxValidation'=>false,
)); ?>

	<?php echo $form->errorSummary($model); ?>

	<div>
		<?php echo $form->labelEx($model,'cost'); ?>
		<?php echo $form->textField($model,'cost'); ?>
		<?php echo $form->error($model,'cost'); ?>
	</div>

	<?php

	echo TbHtml::activeLabel($model, 'productId');
	$this->widget('vendor.anggiaj.eselect2.ESelect2',array(
		'model'=>$model,
		'attribute'=> 'productId',
		'data' => CHtml::listData(Product::model()->findAll(), 'id', 'name'),
		'options' => array(
			'placeholder'=>' -- Выберите продукт -- ', // add this line
		),
		'htmlOptions'=>array(
			'style' => 'width:300px;',
		),
	));

	echo TbHtml::activeLabel($model, 'cityId');
	$this->widget('vendor.anggiaj.eselect2.ESelect2',array(
		'model'=>$model,
		'attribute'=> 'cityId',
		'data' =>CHtml::listData(
			City::model()->findAll(array('order'=>'id')),
			'id',
			function($el){
				return isset($el->translate->name) ? $el->translate->name : '';
			}
		),
		'options' => array(
			'placeholder'=>' -- Выберите город -- ', // add this line
		),
		'htmlOptions'=>array(
			'style' => 'width:300px;',
		),
	));
	?>

	<div style="margin-top:20px;">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Создать' : 'Сохранить'); ?>
	</div>

<?php $this->endWidget(); ?>

protected/modules/priceAdmin/views/productPrice/create.php
<?php
/* @var $this ProductController */
/* @var $model Product */

?>
<h1>Создание продукта</h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/modules/priceAdmin/views/productPrice/index.php
<?php
$ctrl = $this;
$ctrl->widget('application.modules.priceAdmin.components.FieldSetView', array(
    'header' => Yii::t('PriceAdminModule.priceAdmin', 'Продукт'),
    'items' => array(
        array(
            'application.modules.priceAdmin.components.ActionsView',
            'items' => array(
                'products' => array(
                    TbHtml::BUTTON_TYPE_LINK,
                    Yii::t('PriceAdminModule.priceAdmin', 'Карточки продуктов'),
                    array(
                        'url' => $this->createUrl('product/index'),
                        'color' => TbHtml::BUTTON_COLOR_SUCCESS,
                        'style' => 'color:white !important;',
                    )
                ),
                'productsCreate' => array(
                    TbHtml::BUTTON_TYPE_LINK,
                    Yii::t('PriceAdminModule.priceAdmin', 'Создание карточки продукта'),
                    array(
                        'url' => $this->createUrl('product/create'),
                        'color' => TbHtml::BUTTON_COLOR_SUCCESS,
                        'style' => 'color:white !important;',
                    )
                ),
                'productPrices' => array(
                    TbHtml::BUTTON_TYPE_LINK,
                    Yii::t('PriceAdminModule.priceAdmin', 'Продукты'),
                    array(
                        'url' => $this->createUrl('productPrice/index'),
                        'color' => TbHtml::BUTTON_COLOR_INFO,
                        'style' => 'color:white !important;',
                        'class' => 'active',
                    )
                ),
                'productPricesCreate' => array(
                    TbHtml::BUTTON_TYPE_LINK,
                    Yii::t('PriceAdminModule.priceAdmin', 'Создание продукта'),
                    array(
                        'url' => $this->createUrl('productPrice/create'),
                        'color' => TbHtml::BUTTON_COLOR_INFO,
                        'style' => 'color:white !important;',
                    )
                ),
                'categories' => array(
                    TbHtml::BUTTON_TYPE_LINK,
                    Yii::t('PriceAdminModule.priceAdmin', 'Категории'),
                    array(
                        'url' => $this->createUrl('productCategory/index'),
                        'color' => TbHtml::BUTTON_COLOR_PRIMARY,
                        'style' => 'color:white !important;',
                    )
                ),
                'categoryCreate' => array(
                    TbHtml::BUTTON_TYPE_LINK,
                    Yii::t('PriceAdminModule.priceAdmin', 'Создание категории'),
                    array(
                        'url' => $this->createUrl('productCategory/create'),
                        'color' => TbHtml::BUTTON_COLOR_PRIMARY,
                        'style' => 'color:white !important;',
                    )
                ),
            ),
        ),
        array(
            'priceAdmin.widgets.' . get_class($model) . 'GridView',
            'model' => $model,
            'columnsAppend' => array(
                'buttons' => array(
                    'class' => 'bootstrap.widgets.TbButtonColumn',
                    'template' => '<nobr>{update}&#160;{delete}</nobr>',
                    'htmlOptions' => array('style' => 'width: 80px; text-align: left;'),
                    'buttons' => array(
                        'update' => array(
                            'label' => TbHtml::icon(TbHtml::ICON_PENCIL, array('color' => TbHtml::ICON_COLOR_WHITE)),
                            'url' => function ($data) use ($ctrl) {
                                return $ctrl->createUrl('update', array("id" => $data->id));
                            },
                            'options' => array('title' => 'редактировать', 'class' => 'btn btn-small btn-info'),
                        ),
                        'delete' => array(
                            'label' => TbHtml::icon(TbHtml::ICON_PENCIL, array('color' => TbHtml::ICON_COLOR_WHITE)),
                            'url' => function ($data) use ($ctrl) {
                                return $ctrl->createUrl('delete', array("id" => $data->id));
                            },
                            'options' => array('title' => 'удалить', 'class' => 'btn btn-small btn-danger'),
                        ),
                    )
                )
            )
        ),
    )
));
?>

protected/modules/priceAdmin/views/productPrice/update.php
<?php
/* @var $this ProductController */
/* @var $model Product */

?>

<h1>Редактирование значения<?php echo $model->id; ?></h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>